### ISSUE TITLE
Use with parcel

### ISSUE THREAD

**Issue by jnnkB** [taufik-nurrohman/tag-picker#14]
Hi, 

I'm trying to bundle my javascript, css, … with parcel. Unfortunately I couldn't get the tag-picker to work.

When I try to use tag-picker like so:

```js
import "@taufik-nurrohman/tag-picker";

document.addEventListener("DOMContentLoaded", function () {
  new TP(document.querySelector(".tags-field"));
});
```
I get the following error:
```
ReferenceError: TP is not defined script.js:4:2
    parcelRequire<["script.js"]</< script.js:4
```

But when I change the last line of tag-picker to the following it works:
```js
})(window, document, "TP");
```

I don't really know why and if that change will cause other errors. I applied the changes on my own fork (https://github.com/jnnkB/tag-picker) so I could open an pull request if wanted.

Here's a zip that contains all the code: 
[parcel_tag_picker.zip](https://github.com/taufik-nurrohman/tag-picker/files/4748036/parcel_tag_picker.zip)
 
Thanks a lot!

**Comment by taufik-nurrohman** [comment]
It&rsquo;s already there?

https://github.com/taufik-nurrohman/tag-picker/blob/v3.0.10/tag-picker.js#L687

**Comment by taufik-nurrohman** [comment]
Ah, so, Percel environment does not reference the `this` scope to `window`?

**Comment by jnnkB** [comment]
When I create a code snippet containing your code I get the following output:
```
(3) […]
0: Window http://localhost:1234/
1: Object {  }
2: false
length: 3
<prototype>: Array []
```

I don't know why this happens it's just an observation.

**Comment by taufik-nurrohman** [comment]
> I don't know why this happens it's just an observation.

It&rsquo;s a [standard](https://stackoverflow.com/a/30322216/1163000) behavior of ES6 module implementation.

I am mostly making JavaScript plugins for the browsers and have never checked it if it would work with any package bundling system, because personally I don&rsquo;t really like the module concept. I just put that `package.json` file there and then let it go.

Since you are a real user that encounter this problem regarding the ES6 standard and you found out that the only solution to make it work without declaring a UMD-like snippet within my code (that I don&rsquo;t like too), then I would agree to you if you want to make such pull request.

So that I can share this issue to my other JavaScript plugins then. Thanks.
